### PR TITLE
Authorpage simplification

### PR DESCRIPTION
**Pull request by Veldhoen**
removed irrelevant information on publications (scores)
added some relevant information (verantwoordelijkheidsvermelding, ..)
Added role comparison (if author had different role, apply color)
fixed labeling of chart (decades)

### CODE REVIEW

**Review by Haighton — COMMENTED** [review]
Authorpage works good, but the column 'Bijdrage [name author]" (last column of table authorpage) is still showing, but has black background and sometimes chars like: 'aut'. If the info is not relevant for the pilot, maybe better to just hide column?

**Comment by Veldhoen** [comment]
The idea of that column is that you can see the role of the author in the respective publication. For instance, if they were the illustrator in the publication at hand, but acted as translator or author in earlier publications, they are less likely a proper candidate. 

Apparently, this is not very clear on the page. Would it be better to write out the role ('Author' rather than 'aut')? Do you have other suggestions that may clarify the point of this column?

Also, for me the background is not black but rather has the same shade as the rest of the row, unless the role is different/absent in which case the cell is marked - i.e.: colored like a 100% match. I'd like to see if I can reproduce the blackness. Could you add a screenshot where it is black, and provide information on the context: which publication ppn/ author ppn have you opened, and did you fill in the role? And what browser are you using?

**Comment by Haighton** [comment]
I've tried with two different authors. I took a screenshot of 1; this one also has some strange formatting when it comes to pub. titles:

Screenshot 2021-09-20 at 14 42 59

I could try it again with different browser (tried with Chrome).

**Comment by Veldhoen** [comment]
Hmmm weird. The color of that column is generated by a function call to getColorForPercentage(100) in /demosaurus-webapp/demosaurus/static/js/my_functions.js. That should never yield black, but rather green (in the version in this branch) or a kind of orange (in the current master branch). Do you have local changes to my_functions.js perhaps? Does it compile correctly (you can check that in the browser DevTools/Sources)?

**Pull request merged**
